[book]
authors = ["Takanori Fukuyama", "megumish", "Masayuki Kamata"]
language = "ja"
multilingual = false
src = "docs"
title = "Write A TLS on Rust"
[preprocessor.plantuml]
plantuml-cmd = "http://www.plantuml.com/plantuml"
[output.html]
git-repository-url = "https://github.com/quantum-box/learning-with-oss"
